### One hot encoding is used to convert categorical variables into a numeric format so that it can be used by the machine learning algorithms. The basic idea is to create variables that will take up the values 1,0 to represent each categorical value. We do this,as ML algos do not understand text,but only numbers.<a href="#One-hot-encoding-is-used-to-convert-categorical-variables-into-a-numeric-format-so-that-it-can-be-used-by-the-machine-learning-algorithms.--The-basic-idea-is-to-create-variables-that-will-take-up-the-values-1,0-to-represent-each-categorical-value.-We-do-this,as-ML-algos-do-not-understand-text,but-only-numbers." class="anchor-link">¶</a>

In \[ \]:

    # here we are creating our own dataset 

In \[2\]:

    # creating our demo data
    # here we are importing the pandas library for creating the demo data 

    import pandas as pd

In \[5\]:

    # creating our dataframe
    # here we have created the variable called data 
    # then by using the pandas library we have created the dataframe
    # we have created 2 lists in the dictionary 
    # and then we have printed the data 

    data = pd.DataFrame({'Name':['anna','anna','bob','cynthia','cynthia','bob','anna'],
                        'Marks':[56,65,78,99,54,34,88]})
    print(data)

          Name  Marks
    0     anna     56
    1     anna     65
    2      bob     78
    3  cynthia     99
    4  cynthia     54
    5      bob     34
    6     anna     88

In \[6\]:

    # SO we will use one-hot-encoding to convert the names to a numeric counterpart so that our
    # ML algorithm can understand it
    # here we are importing the one hot encoder module from the sklearn.preprocessing package 

    from sklearn.preprocessing import OneHotEncoder

    # create an instance/object from the class OneHotEncoder

    encoder=OneHotEncoder()

    #  here we have the variable caled encoder data 
    #  in the dataframe we will fit and transform  the name column in the data and display
    # it in the form of an array 
    #  so we are fitting the name column 

    encoder_data = pd.DataFrame(encoder.fit_transform(data[['Name']]).toarray())

    # encoding the name and converting it in a 2D array
    #  here the data has been encoded 

    encoder_data

    # 0-is the encoding for the first group 'Anna'
    # 1- is the encoding for the second group 'Bob'
    # 2 - is the encoding for the third group 'Cynthia'

Out\[6\]:

|     | 0   | 1   | 2   |
|-----|-----|-----|-----|
| 0   | 1.0 | 0.0 | 0.0 |
| 1   | 1.0 | 0.0 | 0.0 |
| 2   | 0.0 | 1.0 | 0.0 |
| 3   | 0.0 | 0.0 | 1.0 |
| 4   | 0.0 | 0.0 | 1.0 |
| 5   | 0.0 | 1.0 | 0.0 |
| 6   | 1.0 | 0.0 | 0.0 |

In \[7\]:

    # merging the encoded columns(encoder_data) to the original dataframe
    # here we have created the variable called final data
    #  then we have joined or merged the encoder data to the original data 

    final_data = data.join(encoder_data)

In \[8\]:

    # view the final_data to see if the encoding is done 0=anna,1=bob,2=cynthia
    #  here we have checked the final data  to checj if the categorical variables have been 
    # converted to the numerical 

    final_data

Out\[8\]:

|     | Name    | Marks | 0   | 1   | 2   |
|-----|---------|-------|-----|-----|-----|
| 0   | anna    | 56    | 1.0 | 0.0 | 0.0 |
| 1   | anna    | 65    | 1.0 | 0.0 | 0.0 |
| 2   | bob     | 78    | 0.0 | 1.0 | 0.0 |
| 3   | cynthia | 99    | 0.0 | 0.0 | 1.0 |
| 4   | cynthia | 54    | 0.0 | 0.0 | 1.0 |
| 5   | bob     | 34    | 0.0 | 1.0 | 0.0 |
| 6   | anna    | 88    | 1.0 | 0.0 | 0.0 |

In \[9\]:

    # Drop the original 'Name' variable from our dataframe
    #  here from the final data we have drop the original name column  from the column 
    #  and then we have  printed the final data 
    # axis=0 means rows and axis=1 means columns
    # implace=true makes parmanent changes to the dataframe

    final_data.drop('Name',axis=1,inplace=True)   
    final_data                                    

Out\[9\]:

|     | Marks | 0   | 1   | 2   |
|-----|-------|-----|-----|-----|
| 0   | 56    | 1.0 | 0.0 | 0.0 |
| 1   | 65    | 1.0 | 0.0 | 0.0 |
| 2   | 78    | 0.0 | 1.0 | 0.0 |
| 3   | 99    | 0.0 | 0.0 | 1.0 |
| 4   | 54    | 0.0 | 0.0 | 1.0 |
| 5   | 34    | 0.0 | 1.0 | 0.0 |
| 6   | 88    | 1.0 | 0.0 | 0.0 |

In \[10\]:

    # here we are renaming the column of the dataframe that is the final data 
    # then we have printed the final data 

    final_data.columns =['Marks','Anna','Bob','Cynthia']
    final_data

Out\[10\]:

|     | Marks | Anna | Bob | Cynthia |
|-----|-------|------|-----|---------|
| 0   | 56    | 1.0  | 0.0 | 0.0     |
| 1   | 65    | 1.0  | 0.0 | 0.0     |
| 2   | 78    | 0.0  | 1.0 | 0.0     |
| 3   | 99    | 0.0  | 0.0 | 1.0     |
| 4   | 54    | 0.0  | 0.0 | 1.0     |
| 5   | 34    | 0.0  | 1.0 | 0.0     |
| 6   | 88    | 1.0  | 0.0 | 0.0     |

### This is usually used in NLP(NaturalLanguageProcessing) ,and Sentiment Analysis<a href="#This-is-usually-used-in-NLP(NaturalLanguageProcessing)-,and-Sentiment-Analysis" class="anchor-link">¶</a>

### Encoding is used to transform categorical variable into numeric features. Label Encoding is an easy technique to encode categorical variables. Howver there can be an issue when nominal encoded variables might end up being interpreted as ordinal.<a href="#Encoding-is-used-to-transform-categorical-variable-into-numeric-features.-Label-Encoding-is-an-easy-technique-to-encode-categorical-variables.-Howver-there-can-be-an-issue-when-nominal-encoded-variables-might-end-up-being-interpreted-as-ordinal." class="anchor-link">¶</a>

In \[1\]:

    # techniques used for encoding variables
    # here we are importing the libraies to perform the encoding 

    import pandas as pd
    import numpy as np

In \[2\]:

    # importing the label encoder
    # here we are importing the preprocessing module from the sklearn package 

    from sklearn import preprocessing

In \[11\]:

    # here we have created the variable called iris dataframe 
    # then by using the pandas library we are reading the iris csv file 
    # then we are checking initial 5 rows of the dataframe 

    iris_df = pd.read_csv('Iris.csv')
    iris_df.head()

Out\[11\]:

|     | sepal_length | sepal_width | petal_length | petal_width | species |
|-----|--------------|-------------|--------------|-------------|---------|
| 0   | 5.1          | 3.5         | 1.4          | 0.2         | setosa  |
| 1   | 4.9          | 3.0         | 1.4          | 0.2         | setosa  |
| 2   | 4.7          | 3.2         | 1.3          | 0.2         | setosa  |
| 3   | 4.6          | 3.1         | 1.5          | 0.2         | setosa  |
| 4   | 5.0          | 3.6         | 1.4          | 0.2         | setosa  |

In \[12\]:

    # here we are checking the information present in the dataframe 

    iris_df.info()

    <class 'pandas.core.frame.DataFrame'>
    RangeIndex: 150 entries, 0 to 149
    Data columns (total 5 columns):
     #   Column        Non-Null Count  Dtype  
    ---  ------        --------------  -----  
     0   sepal_length  150 non-null    float64
     1   sepal_width   150 non-null    float64
     2   petal_length  150 non-null    float64
     3   petal_width   150 non-null    float64
     4   species       150 non-null    object 
    dtypes: float64(4), object(1)
    memory usage: 6.0+ KB

In \[6\]:

    # the variable 'species' is a categorical datatype 'object'

### The labelencoder() function is used to convert the categorical variable to its numeric counterpart. in this dataset 'species' is categorical. So we will encode this variable--:<a href="#The-labelencoder()-function-is-used-to-convert-the-categorical-variable-to-its-numeric-counterpart.-in-this-dataset-&#39;species&#39;-is-categorical.-So-we-will-encode-this-variable--:" class="anchor-link">¶</a>

In \[7\]:

    # here we have created the variable called label encoder variable / object from the 
    # label encoder class
    # so we have taken  label encoder from the preprocessing and store it in the label encoder 
    # here the object name is the label encoder 

    label_encoder = preprocessing.LabelEncoder()

In \[9\]:

    # here we are checking the unique values in the species column in the iris dataframe 

    iris_df['species'].unique()

Out\[9\]:

    array(['setosa', 'versicolor', 'virginica'], dtype=object)

In \[10\]:

    # so we need to encode all these 3 categories of the species variable

## The fit_transform() method calculates the mean and variance of each feature and transforms all the features using the respective mean and variance.<a href="#The-fit_transform()-method-calculates-the-mean-and-variance-of-each-feature-and-transforms-all-the-features-using-the-respective-mean-and-variance." class="anchor-link">¶</a>

In \[11\]:

    # here we have created the variable iris_df['species']
    # then we are fitting and transforming the species column of the iris dataframe through the 
    # label encoder 
    # we have used the label encoder to get the numerical value of the categorical values

    iris_df['species'] = label_encoder.fit_transform(iris_df['species'])

In \[46\]:

    # here we have checked the bottom values of the iris dataframe 

    iris_df.tail()

Out\[46\]:

|     | sepal_length | sepal_width | petal_length | petal_width | species |
|-----|--------------|-------------|--------------|-------------|---------|
| 145 | 6.7          | 3.0         | 5.2          | 2.3         | 2       |
| 146 | 6.3          | 2.5         | 5.0          | 1.9         | 2       |
| 147 | 6.5          | 3.0         | 5.2          | 2.0         | 2       |
| 148 | 6.2          | 3.4         | 5.4          | 2.3         | 2       |
| 149 | 5.9          | 3.0         | 5.1          | 1.8         | 2       |

In \[13\]:

    # here we have checked the information present in the iris dataframe 

    iris_df.info()

    <class 'pandas.core.frame.DataFrame'>
    RangeIndex: 150 entries, 0 to 149
    Data columns (total 5 columns):
     #   Column        Non-Null Count  Dtype  
    ---  ------        --------------  -----  
     0   sepal_length  150 non-null    float64
     1   sepal_width   150 non-null    float64
     2   petal_length  150 non-null    float64
     3   petal_width   150 non-null    float64
     4   species       150 non-null    int32  
    dtypes: float64(4), int32(1)
    memory usage: 5.4 KB

## As the dtype of species changes from object --> numeric we can conclude that with LabelEncoder transformation of a categorical variable to a numeric variable can be done<a href="#As-the-dtype-of-species-changes-from-object---%3E-numeric-we-can-conclude-that-with-LabelEncoder-transformation-of-a-categorical-variable-to-a-numeric-variable-can-be-done" class="anchor-link">¶</a>

In \[10\]:

    # here we are importing the libraries for the ONE HOT ENCODING

    import pandas as pd
    import numpy as np

In \[11\]:

    # here we are importing the datasets function from the sklearn package 
    # and also importing the one hot encoder function from the sklearn preprocessing package 

    from sklearn import datasets
    from sklearn.preprocessing import OneHotEncoder

In \[12\]:

    # we need to load the iris dataset to create a dataframe iris_data 
    # y variable which will have our target values

In \[13\]:

    # here we are loading the iris dataset  into the iris data 

    iris_data = datasets.load_iris()

In \[ \]:

    # what is the benifit of using the toy data 
    # you have the data dictionary inbuilt 

In \[14\]:

    # here we are printing the keys present in the iris data 

    print(iris_data.keys())

    dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In \[15\]:

    # here we are checking the feature names present in the iris dataset 
    # here we will get all the independent variables as we are checking fpr the feature names
    # and species is the dependent variable 

    iris_data.feature_names

Out\[15\]:

    ['sepal length (cm)',
     'sepal width (cm)',
     'petal length (cm)',
     'petal width (cm)']

In \[16\]:

    # here wehave checked the target present in the iris dataset 

    iris_data.target

Out\[16\]:

    array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
           1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
           1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
           2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
           2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In \[17\]:

    # here we are slicing the data and then we are compatinating the data 
    # we are having the iris data 
    # by using the pandas dataframe in the data and by using the numpy library we are creating the 
    # iris data which includes the data and target 
    # and we have created the columns which contains the feature names and target 
    # here we are combining because we are creating the data set 
    # then we have created the variable called y 
    #  and then we are pasisng the target values  through iris data and store it in the y 

    iris_data = pd.DataFrame(data=np.c_[iris_data["data"],iris_data["target"]],columns=
                             iris_data["feature_names"]+["target"])
    y = iris_data.target.values

In \[18\]:

    # c_is a function from numpy we use to slice the data and 
    # then concatenate displaying the data and columns in different axis

In \[19\]:

    # here we are checking the initial 2 rows of the iris dataset 

    iris_data.head(2)

Out\[19\]:

|     | sepal length (cm) | sepal width (cm) | petal length (cm) | petal width (cm) | target |
|-----|-------------------|------------------|-------------------|------------------|--------|
| 0   | 5.1               | 3.5              | 1.4               | 0.2              | 0.0    |
| 1   | 4.9               | 3.0              | 1.4               | 0.2              | 0.0    |

In \[20\]:

    # here we are checking the shape of the iris dataset 

    iris_data.shape

Out\[20\]:

    (150, 5)

## the onehotencoder has a feature called 'auto' which determines the categories automatically.<a href="#the-onehotencoder-has-a-feature-called-&#39;auto&#39;-which-determines-the-categories-automatically." class="anchor-link">¶</a>

## reshape function to reshape the array(y) without modifying our data<a href="#reshape-function-to-reshape-the-array(y)-without-modifying-our-data" class="anchor-link">¶</a>

## we also use an 'toarray() which helps us to represent our data in an array format<a href="#we-also-use-an-&#39;toarray()-which-helps-us-to-represent-our-data-in-an-array-format" class="anchor-link">¶</a>

In \[21\]:

    # here we are checking the y variable which is in the form of an array 

    y

Out\[21\]:

    array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
           2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
           2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
           2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In \[22\]:

    # here we have created the variable / object one hot encoder from the class one hot encoder 
    # and we have used (categories='auto') - it is used so that it can determines the category
    # automatically
    # now y is in the array format
    # then we are reshaping the y and fitting and transforming it through the one hot encoder 
    # and store it into the y 
    # -1 means go for any dimenssion and 1 means changing the direction of an array 
    # then we will print the y in the form of an array 

    onehotencoder=OneHotEncoder(categories='auto')
    y = onehotencoder.fit_transform(y.reshape(-1,1))
    print(y.toarray())

    [[1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [1. 0. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 1. 0.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]
     [0. 0. 1.]]

In \[23\]:

    #  the reshaped array will have the resulting array in a single column that is 1D 

In \[24\]:

    # lets find out the categories
    # one hot encoding and creating dummies - there is only 1 difference 
    # when you are creating the dummies you are getting the dummies for  n1 categories 
    # and when you are doing the one hot encoding  then you are creating the numerical 
    # value for every categories 
    # ideally when we are creating the dummy we will get the  one less category 
    # 
    pd.get_dummies(iris_data.target).head()

Out\[24\]:

|     | 0.0 | 1.0 | 2.0 |
|-----|-----|-----|-----|
| 0   | 1   | 0   | 0   |
| 1   | 1   | 0   | 0   |
| 2   | 1   | 0   | 0   |
| 3   | 1   | 0   | 0   |
| 4   | 1   | 0   | 0   |

In \[ \]:

     

In \[ \]: